<?php
return [
    'easy' => [
        ['question' => 'Capital of Japan', 'answer' => 'TOKYO'],
        ['question' => 'Largest continent', 'answer' => 'ASIA'],
        ['question' => 'Currency of the United States', 'answer' => 'DOLLAR'],
        ['question' => 'Largest desert in the world', 'answer' => 'SAHARA'],
        ['question' => 'Chemical symbol for oxygen', 'answer' => 'O'],
        ['question' => 'Primary color of the sky', 'answer' => 'BLUE'],
        ['question' => 'Largest planet in the solar system', 'answer' => 'JUPITER'],
        ['question' => 'Author of "Harry Potter"', 'answer' => 'ROWLING'],
        ['question' => 'National animal of Australia', 'answer' => 'KANGAROO'],
        ['question' => 'First man to step on the moon', 'answer' => 'ARMSTRONG'],
        ['question' => 'Largest bird in the world', 'answer' => 'OSTRICH'],
        ['question' => 'Number of players on a basketball team', 'answer' => 'FIVE'],
        ['question' => 'Chemical symbol for gold', 'answer' => 'AU'],
        ['question' => 'Fastest land animal', 'answer' => 'CHEETAH'],
        ['question' => 'Largest freshwater lake by surface area', 'answer' => 'SUPERIOR'],
        ['question' => 'Inventor of the light bulb', 'answer' => 'EDISON'],
        ['question' => 'Capital of Italy', 'answer' => 'ROME'],
        ['question' => 'Number of continents on Earth', 'answer' => 'SEVEN'],
        ['question' => 'Author of "The Hobbit"', 'answer' => 'TOLKIEN'],
        ['question' => 'Chemical symbol for carbon', 'answer' => 'C'],
    ],
    'medium' => [
        ['question' => 'Author of "Romeo and Juliet"', 'answer' => 'SHAKESPEARE'],
        ['question' => 'Number of sides on a triangle', 'answer' => 'THREE'],
        ['question' => 'Largest moon of Saturn', 'answer' => 'TITAN'],
        ['question' => 'Scientific study of the earth', 'answer' => 'GEOLOGY'],
        ['question' => 'National flower of Japan', 'answer' => 'CHERRY BLOSSOM'],
        ['question' => 'Author of "The Great Gatsby"', 'answer' => 'FITZGERALD'],
        ['question' => 'Chemical symbol for iron', 'answer' => 'FE'],
        ['question' => 'Inventor of the telephone', 'answer' => 'BELL'],
        ['question' => 'Longest river in Africa', 'answer' => 'NILE'],
        ['question' => 'Country with the longest coastline', 'answer' => 'CANADA'],
        ['question' => 'Year the Berlin Wall fell', 'answer' => 'NINETEEN EIGHTY NINE'],
        ['question' => 'Author of "War and Peace"', 'answer' => 'TOLSTOY'],
        ['question' => 'Chemical symbol for silver', 'answer' => 'AG'],
        ['question' => 'Largest organ in the human body', 'answer' => 'SKIN'],
        ['question' => 'Year the Declaration of Independence was signed', 'answer' => 'SEVENTEEN SEVENTY SIX'],
        ['question' => 'Scientist who developed the theory of relativity', 'answer' => 'EINSTEIN'],
        ['question' => 'Country with the largest population', 'answer' => 'CHINA'],
        ['question' => 'Chemical symbol for helium', 'answer' => 'HE'],
        ['question' => 'Number of players on a baseball team', 'answer' => 'NINE'],
    ],
    'hard' => [
        ['question' => 'First person to walk on the moon', 'answer' => 'ARMSTRONG'],
        ['question' => 'Chemical symbol for sodium chloride', 'answer' => 'SALT'],
        ['question' => 'Longest river in the world', 'answer' => 'AMAZON'],
        ['question' => 'Year the Eiffel Tower was completed', 'answer' => 'EIGHTEEN EIGHTY NINE'],
        ['question' => 'Author of "The Catcher in the Rye"', 'answer' => 'SALINGER'],
        ['question' => 'Chemical symbol for potassium', 'answer' => 'K'],
        ['question' => 'Largest island in the world', 'answer' => 'GREENLAND'],
        ['question' => 'Year World War I began', 'answer' => 'NINETEEN FOURTEEN'],
        ['question' => 'Chemical symbol for copper', 'answer' => 'CU'],
        ['question' => 'Tallest mountain in the world', 'answer' => 'EVEREST'],
        ['question' => 'Author of "To Kill a Mockingbird"', 'answer' => 'LEE'],
        ['question' => 'Chemical symbol for lead', 'answer' => 'PB'],
        ['question' => 'Number of planets in the solar system', 'answer' => 'EIGHT'],
        ['question' => 'Country with the highest GDP', 'answer' => 'UNITED STATES'],
        ['question' => 'Chemical symbol for tin', 'answer' => 'SN'],
        ['question' => 'Year the Great Depression began', 'answer' => 'NINETEEN TWENTY NINE'],
        ['question' => 'Largest ocean', 'answer' => 'PACIFIC'],
        ['question' => 'Country with the most time zones', 'answer' => 'FRANCE'],
        ['question' => 'Chemical symbol for nitrogen', 'answer' => 'N'],
        ['question' => 'First woman to win a Nobel Prize', 'answer' => 'CURIE'],
    ]
];
?>